### PR TITLE
Implement redial for transport channels

### LINKED ISSUE #28: Allow reconnection of transport channels
If we have a TCP or TLS client and server with two transport channels between them, and for one of them the link is unavailable (i.e., no data is transmitted), all communication should use the other transport channel. After the link becomes available again, we should try to reconnect the transport channel. In this process, no errors or `abort()`s should happen.

There are already `transport_redial()` methods implemented for TCP/TLS, but these are currently not used.

### PR DESCRIPTION
**Pull request by laugengebaeck**
This closes #28.

Please note: The function signatures of `redundancy_mux_send`, `transport_connect` and `transport_redial` have changed!

### CODE REVIEW

**Review by rs22 — APPROVED** [review]
Looks good, thanks!

**Comment by rs22** [comment]
@laugengebaeck Could you have another look into the merge conflicts? Thanks!

**Comment by rs22** [comment]
Maybe you can also post your tcpkill command here so I know how we can test this.

**Comment by laugengebaeck** [comment]
The tcpkill command was

```bash
tcpkill -i lo port 9999
```

It kills all established TCP connections on the lo (loopback, because sender and receiver communicate only on the local device) interface which contain the port 9999 (the second transport channel of the sender/client). However, performing a TCP handshake is still possible, only that the established connection will immediately be killed.

**Pull request merged**
